accepted = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "CC0-1.0",
    "MPL-2.0",
    "ISC",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "Unicode-DFS-2016",
    "BSL-1.0",
    "NCSA",
]
