[package]
authors = ["stuncloud <stuncloud@gmail.com>"]
edition = "2018"
name = "uwscr"
version = "0.1.9"
build = "build.rs"

[dependencies]
enigo = "*"
cast = "0.2.3"
encoding_rs = "0.8.26"
regex = "1"
strum = "0.20"
strum_macros = "0.20"
num-traits = "0.2"
num-derive = "0.3"
indexmap = "1.6.0"
serde_json = "1.0"
chrono = "0.4"
bincode = "1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
windows = "0.10"
dlopen = "0.1"
libffi = "1.0.1"
libc = "0.2"

[build-dependencies]
winres = "0.1"
windows = "0.10"

[package.metadata.wix]
compiler-args = ["-nologo"]
culture = "ja-JP"
linker-args = ["-nologo"]
no-build = true