[package]
authors = ["stuncloud <stuncloud@gmail.com>"]
edition = "2018"
name = "uwscr"
version = "0.0.3"
build = "build.rs"

[dependencies]
structopt = "0.3.18"

[build-dependencies]
winres = "0.1"

