[package]
authors = ["stuncloud <stuncloud@gmail.com>"]
edition = "2021"
name = "uwscr"
version = "0.11.0"
build = "build.rs"
rust-version = "1.65"

[features]
default = []
chkimg = ["opencv"]

[dependencies]
base64 = "0.21.0"
bincode = "1"
cast = "0.3.0"
chrono = {version = "0.4.24", features = ["unstable-locales"]}
csv = "1.1"
dlopen = "0.1"
encoding_rs = "0.8"
htmlentity = "1.2.0"
indexmap = "1.9"
kanaria = "0.2.0"
libc = "0.2"
libffi = "3.2.0"
num-derive = "0.3"
num-traits = "0.2"
once_cell = "1"
opencv = { version = "0.74.0", default-features = false, features = ["imgcodecs", "imgproc"], optional = true}
regex = "1"
reqwest = { version = "0.11", features = ["blocking"] }
schemars = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
stacker = "0.1.14"
strum = "0.24"
strum_macros = "0.24"
tungstenite = "0.18.0"
url = "2.2.2"
urlencoding = "2.1.0"
winreg = "0.11"
wmi = "0.12.1"
zip = "0.6.2"
scraper = "0.15.0"
rand = "0.8.5"

[build-dependencies]
winres = "0.1"

[dependencies.windows]
version = "0.48.0"
features = [
    "Win32_Devices_Sensors",
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_Media_Audio",
    "Win32_Media_Speech",
    # "Win32_Media_Multimedia",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Console",
    "Win32_System_DataExchange",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_Ole",
    "Win32_System_Power",
    "Win32_System_ProcessStatus",
    "Win32_System_Shutdown",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_UI_Accessibility",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_Ime",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Input_Pointer",
    "Win32_UI_Shell",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_UI_WindowsAndMessaging",
]

[package.metadata.wix]
compiler-args = ["-nologo"]
culture = "ja-JP"
linker-args = ["-nologo"]
no-build = true
