[package]
authors = ["stuncloud <stuncloud@gmail.com>"]
edition = "2018"
name = "uwscr"
version = "0.0.4"
build = "build.rs"

[dependencies]
structopt = "0.3.18"
enigo = "*"
cast = "0.2.3"

[dependencies.winapi]
version = "0.3.9"
features = [
    "winuser",
    "windef",
]

[build-dependencies]
winres = "0.1"

