[package]
authors = ["stuncloud <stuncloud@gmail.com>"]
edition = "2021"
name = "uwscr"
version = "0.8.0"
build = "build.rs"

[features]
default = []
chkimg = ["opencv"]

[dependencies]
enigo = "*"
cast = "0.2.3"
encoding_rs = "0.8.26"
regex = "1.5"
strum = "0.20"
strum_macros = "0.20"
num-traits = "0.2"
num-derive = "0.3"
indexmap = "1.6.0"
serde_json = "1.0"
chrono = "0.4"
bincode = "1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
dlopen = "0.1"
libffi = "1.0.1"
libc = "0.2"
schemars = "0.8.6"
url = "2.2.2"
winreg = "0.10"
reqwest = { version = "0.11.6", features = ["blocking"] }
tungstenite = "0.16.0"
wmi = "0.9"
opencv = { version = "0.60.0", default-features = false, features = ["imgcodecs", "imgproc"], optional = true}
base64 = "0.13.0"
once_cell = "1.9.0"
csv = "1.1"
zip = "0.6.2"
kanaria = "0.2.0"
urlencoding = "2.1.0"
htmlentity = "1.2.0"
stacker = "0.1.14"

[build-dependencies]
winres = "0.1"

[dependencies.windows]
version = "0.35.0"
features = [
    "alloc",
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Console",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_System_Ole",
    "Win32_System_ProcessStatus",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_System_WindowsProgramming",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Controls",
]

[package.metadata.wix]
compiler-args = ["-nologo"]
culture = "ja-JP"
linker-args = ["-nologo"]
no-build = true