[package]
authors = ["stuncloud <stuncloud@gmail.com>"]
edition = "2018"
name = "uwscr"
version = "0.2.1"
build = "build.rs"

[dependencies]
enigo = "*"
cast = "0.2.3"
encoding_rs = "0.8.26"
regex = "1"
strum = "0.20"
strum_macros = "0.20"
num-traits = "0.2"
num-derive = "0.3"
indexmap = "1.6.0"
serde_json = "1.0"
chrono = "0.4"
bincode = "1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
dlopen = "0.1"
libffi = "1.0.1"
libc = "0.2"
schemars = "0.8.6"
url = "2.2.2"
winreg = "0.10"
reqwest = { version = "0.11", features = ["blocking"] }
websocket = "0.24"
wmi = "0.9"

[build-dependencies]
winres = "0.1"

[dependencies.windows]
version = "0.23.0"
features = [
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_System_OleAutomation",
    "Win32_System_ProcessStatus",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_UI_HiDpi",
    "Win32_UI_KeyboardAndMouseInput",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
]

[package.metadata.wix]
compiler-args = ["-nologo"]
culture = "ja-JP"
linker-args = ["-nologo"]
no-build = true