[package]
authors = ["stuncloud <stuncloud@gmail.com>"]
edition = "2018"
name = "uwscr"
version = "0.0.7"
build = "build.rs"

[dependencies]
structopt = "0.3.18"
enigo = "*"
cast = "0.2.3"
encoding_rs = "0.8.26"
regex = "1"
strum = "0.20"
strum_macros = "0.20"
num-traits = "0.2"
num-derive = "0.3"

[dependencies.winapi]
version = "0.3.9"
features = [
    "winuser",
    "windef",
    "winnt",
    "dwmapi",
    "psapi",
    "processthreadsapi",
    "libloaderapi",
    "handleapi",
    "wingdi",
    "wow64apiset",
    "sysinfoapi",
]

[build-dependencies]
winres = "0.1"

