name: バグを報告する
description: 不具合報告はこちら
labels: ["bug"]
assignees: stuncloud
body:
  - type: textarea
    attributes:
      label: 概要
      description: 不具合の概要を簡潔に記入してください
    validations:
      required: true
  - type: textarea
    attributes:
      label: 再現スクリプト
      description: >
        不具合が発生する、または発生する可能性のあるコードを記入してください
      render: Stylus
  - type: textarea
    attributes:
      label: 再現手順
      description: >
        スクリプト実行以外で発生する不具合の場合に再現手順を記してください
  - type: textarea
    attributes:
      label: 回避方法
      description: >
        現象を回避するための方法や代替コードがあれば記入してください
  - type: textarea
    attributes:
      label: 備考
      description: >
        その他に付随する情報がある場合に記入してください
  - type: dropdown
    attributes:
      label: バージョン
      description: 不具合が発生したUWSCRのバージョンを選択してください
      default: 0
      options:
        - "1.0.4"
        - "1.0.3"
        - "1.0.2"
        - "1.0.1"
        - "1.0.0"
        - "0.16.1"
        - "その他"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 不具合発生環境
      description: 特定の環境で不具合が発生する場合は実行環境(OS)を選択してください
      multiple: true
      default: 0
      options:
        - "環境は問わない"
        - "Windows 10"
        - "Windows 11"
        - "Windows 12"
        - "その他"