name: 要望を伝える
description: 機能や仕様に関する要望はこちら
labels: ["enhancement"]
assignees: stuncloud
body:
  - type: textarea
    attributes:
      label: 概要
      description: 追加してほしい機能や改善点について簡潔に記述してください
    validations:
      required: true
  - type: textarea
    attributes:
      label: 理由
      description: その機能を要望する理由を記述してください
    validations:
      required: true
  - type: textarea
    attributes:
      label: 実装例
      description: 実装例として挙げたいコードがあれば記述してください
      render: Stylus